spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

bot:
  token: {TOKEN}

event-handler-thread-pool:
  message-event:
    queueCapacity: 1000
    maxPoolSize: 10
    corePoolSize: 10
    threadNamePrefix: message_event-